/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreateDocumentResultFromDiscriminatorValue, createGetDocumentsResultFromDiscriminatorValue, serializeCreateDocumentRequest, serializeCreateDocumentResult, type CreateDocumentRequest, type CreateDocumentResult, type GetDocumentsResult } from '../models/index.js';
// @ts-ignore
import { DocumentsItemRequestBuilderNavigationMetadata, DocumentsItemRequestBuilderRequestsMetadata, type DocumentsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /documents
 */
export interface DocumentsRequestBuilder extends BaseRequestBuilder<DocumentsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.documents.item collection
     * @param id Unique identifier of the item
     * @returns {DocumentsItemRequestBuilder}
     */
     byId(id: number) : DocumentsItemRequestBuilder;
    /**
     * Returns a paginated list of documents for the current user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GetDocumentsResult[]>}
     */
     get(requestConfiguration?: RequestConfiguration<DocumentsRequestBuilderGetQueryParameters> | undefined) : Promise<GetDocumentsResult[] | undefined>;
    /**
     * Creates a new document and enqueues a GeneratePdf command.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateDocumentResult>}
     */
     post(body: CreateDocumentRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateDocumentResult | undefined>;
    /**
     * Returns a paginated list of documents for the current user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DocumentsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Creates a new document and enqueues a GeneratePdf command.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateDocumentRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Returns a paginated list of documents for the current user.
 */
export interface DocumentsRequestBuilderGetQueryParameters {
    page?: number;
    pageSize?: number;
}
/**
 * Uri template for the request builder.
 */
export const DocumentsRequestBuilderUriTemplate = "{+baseurl}/documents{?page*,pageSize*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DocumentsRequestBuilderNavigationMetadata: Record<Exclude<keyof DocumentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: DocumentsItemRequestBuilderRequestsMetadata,
        navigationMetadata: DocumentsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DocumentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DocumentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createGetDocumentsResultFromDiscriminatorValue,
    },
    post: {
        uriTemplate: DocumentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createCreateDocumentResultFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateDocumentRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
