/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision current user
         * @description Returns the current Core user ID, provisioning the user from the validated Portal JWT when needed.
         */
        post: operations["ProvisionUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/job-listings/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search job listings
         * @description Proxies to TheirStack POST /v1/jobs/search and returns matching job listings.
         */
        post: operations["SearchJobListings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List documents
         * @description Returns a paginated list of documents for the current user.
         */
        get: operations["GetDocuments"];
        put?: never;
        /**
         * Create document
         * @description Creates a new document and enqueues a GeneratePdf command.
         */
        post: operations["CreateDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get document
         * @description Returns a single document by ID for the current user.
         */
        get: operations["GetDocumentById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get download URL
         * @description Generates a short-lived signed URL for downloading the PDF. Requires document status Succeeded.
         */
        post: operations["GetDownloadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/app/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get provider usage
         * @description Returns the current provider usage and quota for the current user.
         */
        get: operations["GetUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnonymousTypeOflong: {
            /** Format: int64 */
            userId: number;
        };
        CreateDocumentRequest: {
            templateKey: string;
            /** Format: int32 */
            templateVersion: null | number;
            payloadJson: string;
        };
        CreateDocumentResult: {
            /** Format: int64 */
            documentId: number;
            status: string;
        };
        GetDocumentsResult: {
            /** Format: int64 */
            id: number;
            status: string;
            templateKey: string;
            errorCode: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SearchJobListingsRequest: {
            skills: string[];
            sourceDomains: string[];
            /**
             * Format: int32
             * @default 0
             */
            page: number;
            /**
             * Format: int32
             * @default 25
             */
            pageSize: number;
            jobTitles?: null | string[];
            descriptionKeywords?: null | string[];
            remote?: null | boolean;
            seniorities?: null | string[];
            employmentTypes?: null | string[];
            countries?: null | string[];
            /** Format: double */
            minSalaryUsd?: null | number;
            /** Format: double */
            maxSalaryUsd?: null | number;
            /**
             * Format: int32
             * @default 30
             */
            postedWithinDays: number;
            companyNames?: null | string[];
        };
        SearchJobListingsResult: {
            /** Format: int64 */
            id: number;
            title: string;
            companyName: string;
            companyLogoUrl: null | string;
            location: null | string;
            remote: boolean;
            salaryString: null | string;
            technologySlugs: string[];
            description: null | string;
            url: string;
            sourceUrl: null | string;
            datePosted: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ProvisionUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonymousTypeOflong"];
                };
            };
        };
    };
    SearchJobListings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchJobListingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchJobListingsResult"][];
                };
            };
        };
    };
    GetDocuments: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDocumentsResult"][];
                };
            };
        };
    };
    CreateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDocumentResult"];
                };
            };
        };
    };
    GetDocumentById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
