/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DownloadUrlRequestBuilderRequestsMetadata, type DownloadUrlRequestBuilder } from './downloadUrl/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /documents/{id}
 */
export interface DocumentsItemRequestBuilder extends BaseRequestBuilder<DocumentsItemRequestBuilder> {
    /**
     * The downloadUrl property
     */
    get downloadUrl(): DownloadUrlRequestBuilder;
    /**
     * Returns a single document by ID for the current user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Returns a single document by ID for the current user.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DocumentsItemRequestBuilderUriTemplate = "{+baseurl}/documents/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DocumentsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof DocumentsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    downloadUrl: {
        requestsMetadata: DownloadUrlRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DocumentsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DocumentsItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
