/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SearchRequestBuilderRequestsMetadata, type SearchRequestBuilder } from './search/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /job-listings
 */
export interface JobListingsRequestBuilder extends BaseRequestBuilder<JobListingsRequestBuilder> {
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const JobListingsRequestBuilderUriTemplate = "{+baseurl}/job-listings";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const JobListingsRequestBuilderNavigationMetadata: Record<Exclude<keyof JobListingsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    search: {
        requestsMetadata: SearchRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
