/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /documents/{id}/download-url
 */
export interface DownloadUrlRequestBuilder extends BaseRequestBuilder<DownloadUrlRequestBuilder> {
    /**
     * Generates a short-lived signed URL for downloading the PDF. Requires document status Succeeded.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Generates a short-lived signed URL for downloading the PDF. Requires document status Succeeded.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DownloadUrlRequestBuilderUriTemplate = "{+baseurl}/documents/{id}/download-url";
/**
 * Metadata for all the requests in the request builder.
 */
export const DownloadUrlRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DownloadUrlRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
