/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateDocumentRequest}
 */
// @ts-ignore
export function createCreateDocumentRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateDocumentRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateDocumentResult}
 */
// @ts-ignore
export function createCreateDocumentResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateDocumentResult;
}
export interface CreateDocumentRequest extends AdditionalDataHolder, Parsable {
    /**
     * The payloadJson property
     */
    payloadJson?: string | null;
    /**
     * The templateKey property
     */
    templateKey?: string | null;
    /**
     * The templateVersion property
     */
    templateVersion?: number | null;
}
export interface CreateDocumentResult extends AdditionalDataHolder, Parsable {
    /**
     * The documentId property
     */
    documentId?: number | null;
    /**
     * The status property
     */
    status?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {GetDocumentsResult}
 */
// @ts-ignore
export function createGetDocumentsResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoGetDocumentsResult;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SearchJobListingsRequest}
 */
// @ts-ignore
export function createSearchJobListingsRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSearchJobListingsRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {SearchJobListingsResult}
 */
// @ts-ignore
export function createSearchJobListingsResultFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSearchJobListingsResult;
}
/**
 * The deserialization information for the current model
 * @param CreateDocumentRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateDocumentRequest(createDocumentRequest: Partial<CreateDocumentRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "payloadJson": n => { createDocumentRequest.payloadJson = n.getStringValue(); },
        "templateKey": n => { createDocumentRequest.templateKey = n.getStringValue(); },
        "templateVersion": n => { createDocumentRequest.templateVersion = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateDocumentResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateDocumentResult(createDocumentResult: Partial<CreateDocumentResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "documentId": n => { createDocumentResult.documentId = n.getNumberValue(); },
        "status": n => { createDocumentResult.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param GetDocumentsResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoGetDocumentsResult(getDocumentsResult: Partial<GetDocumentsResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { getDocumentsResult.createdAt = n.getDateValue(); },
        "errorCode": n => { getDocumentsResult.errorCode = n.getStringValue(); },
        "id": n => { getDocumentsResult.id = n.getNumberValue(); },
        "status": n => { getDocumentsResult.status = n.getStringValue(); },
        "templateKey": n => { getDocumentsResult.templateKey = n.getStringValue(); },
        "updatedAt": n => { getDocumentsResult.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SearchJobListingsRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSearchJobListingsRequest(searchJobListingsRequest: Partial<SearchJobListingsRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "page": n => { searchJobListingsRequest.page = n.getNumberValue(); },
        "pageSize": n => { searchJobListingsRequest.pageSize = n.getNumberValue(); },
        "skills": n => { searchJobListingsRequest.skills = n.getCollectionOfPrimitiveValues<string>(); },
        "sourceDomains": n => { searchJobListingsRequest.sourceDomains = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param SearchJobListingsResult The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSearchJobListingsResult(searchJobListingsResult: Partial<SearchJobListingsResult> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "companyLogoUrl": n => { searchJobListingsResult.companyLogoUrl = n.getStringValue(); },
        "companyName": n => { searchJobListingsResult.companyName = n.getStringValue(); },
        "datePosted": n => { searchJobListingsResult.datePosted = n.getStringValue(); },
        "description": n => { searchJobListingsResult.description = n.getStringValue(); },
        "id": n => { searchJobListingsResult.id = n.getNumberValue(); },
        "location": n => { searchJobListingsResult.location = n.getStringValue(); },
        "remote": n => { searchJobListingsResult.remote = n.getBooleanValue(); },
        "salaryString": n => { searchJobListingsResult.salaryString = n.getStringValue(); },
        "sourceUrl": n => { searchJobListingsResult.sourceUrl = n.getStringValue(); },
        "technologySlugs": n => { searchJobListingsResult.technologySlugs = n.getCollectionOfPrimitiveValues<string>(); },
        "title": n => { searchJobListingsResult.title = n.getStringValue(); },
        "url": n => { searchJobListingsResult.url = n.getStringValue(); },
    }
}
export interface GetDocumentsResult extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: Date | null;
    /**
     * The errorCode property
     */
    errorCode?: string | null;
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The status property
     */
    status?: string | null;
    /**
     * The templateKey property
     */
    templateKey?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface SearchJobListingsRequest extends AdditionalDataHolder, Parsable {
    /**
     * The page property
     */
    page?: number | null;
    /**
     * The pageSize property
     */
    pageSize?: number | null;
    /**
     * The skills property
     */
    skills?: string[] | null;
    /**
     * The sourceDomains property
     */
    sourceDomains?: string[] | null;
}
export interface SearchJobListingsResult extends AdditionalDataHolder, Parsable {
    /**
     * The companyLogoUrl property
     */
    companyLogoUrl?: string | null;
    /**
     * The companyName property
     */
    companyName?: string | null;
    /**
     * The datePosted property
     */
    datePosted?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The location property
     */
    location?: string | null;
    /**
     * The remote property
     */
    remote?: boolean | null;
    /**
     * The salaryString property
     */
    salaryString?: string | null;
    /**
     * The sourceUrl property
     */
    sourceUrl?: string | null;
    /**
     * The technologySlugs property
     */
    technologySlugs?: string[] | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The url property
     */
    url?: string | null;
}
/**
 * Serializes information the current object
 * @param CreateDocumentRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateDocumentRequest(writer: SerializationWriter, createDocumentRequest: Partial<CreateDocumentRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createDocumentRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("payloadJson", createDocumentRequest.payloadJson);
    writer.writeStringValue("templateKey", createDocumentRequest.templateKey);
    writer.writeNumberValue("templateVersion", createDocumentRequest.templateVersion);
    writer.writeAdditionalData(createDocumentRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateDocumentResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateDocumentResult(writer: SerializationWriter, createDocumentResult: Partial<CreateDocumentResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createDocumentResult || isSerializingDerivedType) { return; }
    writer.writeNumberValue("documentId", createDocumentResult.documentId);
    writer.writeStringValue("status", createDocumentResult.status);
    writer.writeAdditionalData(createDocumentResult.additionalData);
}
/**
 * Serializes information the current object
 * @param GetDocumentsResult The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeGetDocumentsResult(writer: SerializationWriter, getDocumentsResult: Partial<GetDocumentsResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!getDocumentsResult || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdAt", getDocumentsResult.createdAt);
    writer.writeStringValue("errorCode", getDocumentsResult.errorCode);
    writer.writeNumberValue("id", getDocumentsResult.id);
    writer.writeStringValue("status", getDocumentsResult.status);
    writer.writeStringValue("templateKey", getDocumentsResult.templateKey);
    writer.writeDateValue("updatedAt", getDocumentsResult.updatedAt);
    writer.writeAdditionalData(getDocumentsResult.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SearchJobListingsRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSearchJobListingsRequest(writer: SerializationWriter, searchJobListingsRequest: Partial<SearchJobListingsRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!searchJobListingsRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("page", searchJobListingsRequest.page);
    writer.writeNumberValue("pageSize", searchJobListingsRequest.pageSize);
    writer.writeCollectionOfPrimitiveValues<string>("skills", searchJobListingsRequest.skills);
    writer.writeCollectionOfPrimitiveValues<string>("sourceDomains", searchJobListingsRequest.sourceDomains);
    writer.writeAdditionalData(searchJobListingsRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param SearchJobListingsResult The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSearchJobListingsResult(writer: SerializationWriter, searchJobListingsResult: Partial<SearchJobListingsResult> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!searchJobListingsResult || isSerializingDerivedType) { return; }
    writer.writeStringValue("companyLogoUrl", searchJobListingsResult.companyLogoUrl);
    writer.writeStringValue("companyName", searchJobListingsResult.companyName);
    writer.writeStringValue("datePosted", searchJobListingsResult.datePosted);
    writer.writeStringValue("description", searchJobListingsResult.description);
    writer.writeNumberValue("id", searchJobListingsResult.id);
    writer.writeStringValue("location", searchJobListingsResult.location);
    writer.writeBooleanValue("remote", searchJobListingsResult.remote);
    writer.writeStringValue("salaryString", searchJobListingsResult.salaryString);
    writer.writeStringValue("sourceUrl", searchJobListingsResult.sourceUrl);
    writer.writeCollectionOfPrimitiveValues<string>("technologySlugs", searchJobListingsResult.technologySlugs);
    writer.writeStringValue("title", searchJobListingsResult.title);
    writer.writeStringValue("url", searchJobListingsResult.url);
    writer.writeAdditionalData(searchJobListingsResult.additionalData);
}
/* tslint:enable */
/* eslint-enable */
