/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type UsageRequestBuilder, UsageRequestBuilderRequestsMetadata } from './usage/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /app
 */
export interface AppRequestBuilder extends BaseRequestBuilder<AppRequestBuilder> {
    /**
     * The usage property
     */
    get usage(): UsageRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AppRequestBuilderUriTemplate = "{+baseurl}/app";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AppRequestBuilderNavigationMetadata: Record<Exclude<keyof AppRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    usage: {
        requestsMetadata: UsageRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
